version: "1"

services:
  web:
    image: node
    env_file:
      - ./docker/node.js/.env
      - ./.env
    command: node --harmony --debug app.js
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - redis
  redis:
    image: redis
    container_name: ${REDIS_HOST}
    volumes:
      - ./docker/redis/data:/data
