version: "2"

services:
  redis:
    build: ./docker/redis
    container_name: ${REDIS_HOST}
    volumes:
      - ./docker/redis/data:/data
  webapp:
    build: .
    env_file:
      - ./docker/node.js/.env
      - ./.env
    command: node --harmony --debug app.js
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/webapp
    working_dir: /webapp
    depends_on:
      - redis